# Generated by Django 3.0.6 on 2021-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Councelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=500)),
                ('session_date', models.CharField(max_length=100)),
                ('session_time', models.CharField(max_length=100)),
            ],
        ),
    ]
